-- ============================================================
-- Feijó Market — Configuração do banco de dados
-- Cole TODO este arquivo no Supabase: SQL Editor → New query → Run
-- ============================================================

-- 1) Papéis de usuário (admin / cliente)
create type public.app_role as enum ('admin', 'customer');

create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  role public.app_role not null,
  unique (user_id, role)
);

grant select on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
alter table public.user_roles enable row level security;

create or replace function public.has_role(_user_id uuid, _role public.app_role)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.user_roles where user_id = _user_id and role = _role)
$$;

create policy "Usuário vê o próprio papel" on public.user_roles
  for select to authenticated using (auth.uid() = user_id);

-- 2) Todo novo cadastro vira cliente; o e-mail do dono vira admin
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.user_roles (user_id, role) values (new.id, 'customer');
  if new.email = 'francdenisbr@gmail.com' then
    insert into public.user_roles (user_id, role) values (new.id, 'admin');
  end if;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 3) Catálogo de produtos
create table public.products (
  id text primary key,
  slug text unique not null,
  name text not null,
  brand text not null,
  category text not null,
  subcategory text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  sale_price numeric(10,2) check (sale_price is null or sale_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  rating numeric(2,1) not null default 0,
  review_count integer not null default 0,
  image_url text not null default '',
  variants jsonb not null default '[]'::jsonb,
  colors text[],
  sizes text[],
  specs jsonb not null default '{}'::jsonb,
  tags text[] not null default '{}',
  source text not null default 'own',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_category_idx on public.products (category);
create index products_slug_idx on public.products (slug);

grant select on public.products to anon;
grant select on public.products to authenticated;
grant insert, update, delete on public.products to authenticated;
grant all on public.products to service_role;

alter table public.products enable row level security;

create policy "Catálogo público para leitura" on public.products
  for select to anon, authenticated using (true);

create policy "Só admin insere produtos" on public.products
  for insert to authenticated with check (public.has_role(auth.uid(), 'admin'));

create policy "Só admin edita produtos" on public.products
  for update to authenticated using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

create policy "Só admin apaga produtos" on public.products
  for delete to authenticated using (public.has_role(auth.uid(), 'admin'));

-- 4) Produtos atuais da loja
INSERT INTO public.products (id, slug, name, brand, category, subcategory, description, price, sale_price, stock, rating, review_count, image_url, variants, colors, sizes, specs, tags, source) VALUES
('p001','whey-protein-isolado-900g','Whey Protein Isolado 900g','MaxForce','suplementos','Whey','Whey Protein Isolado 900g da MaxForce: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para whey e para elevar sua rotina.',249.9,199.9,42,4.8,1284,'','[{"label":"Sabor","options":["Chocolate","Baunilha","Morango","Cookies"]}]'::jsonb,NULL,NULL,'{"Marca":"MaxForce","Categoria":"Whey","Código":"FS-1000","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p002','whey-protein-concentrado-1kg','Whey Protein Concentrado 1kg','Nutrion','suplementos','Whey','Whey Protein Concentrado 1kg da Nutrion: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para whey e para elevar sua rotina.',169.9,NULL,80,4.6,932,'','[{"label":"Sabor","options":["Chocolate","Baunilha","Morango","Cookies"]}]'::jsonb,NULL,NULL,'{"Marca":"Nutrion","Categoria":"Whey","Código":"FS-1001","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p003','whey-3w-blend-2kg','Whey 3W Blend 2kg','IronLab','suplementos','Whey','Whey 3W Blend 2kg da IronLab: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para whey e para elevar sua rotina.',289.9,259.9,15,4.5,411,'','[{"label":"Sabor","options":["Chocolate","Baunilha","Morango","Cookies"]}]'::jsonb,NULL,NULL,'{"Marca":"IronLab","Categoria":"Whey","Código":"FS-1002","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p004','creatina-monohidratada-300g','Creatina Monohidratada 300g','MaxForce','suplementos','Creatina','Creatina Monohidratada 300g da MaxForce: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para creatina e para elevar sua rotina.',129.9,89.9,120,4.9,2210,'','[]'::jsonb,NULL,NULL,'{"Marca":"MaxForce","Categoria":"Creatina","Código":"FS-1003","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p005','creatina-creapure-250g','Creatina Creapure 250g','Nutrion','suplementos','Creatina','Creatina Creapure 250g da Nutrion: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para creatina e para elevar sua rotina.',159.9,NULL,34,4.8,640,'','[]'::jsonb,NULL,NULL,'{"Marca":"Nutrion","Categoria":"Creatina","Código":"FS-1004","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p006','multivitaminico-a-z-120-caps','Multivitamínico A-Z 120 caps','VitaPlus','suplementos','Vitaminas','Multivitamínico A-Z 120 caps da VitaPlus: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para vitaminas e para elevar sua rotina.',79.9,64.9,200,4.7,518,'','[]'::jsonb,NULL,NULL,'{"Marca":"VitaPlus","Categoria":"Vitaminas","Código":"FS-1005","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p007','vitamina-d3-2000ui-60-caps','Vitamina D3 2000UI 60 caps','VitaPlus','suplementos','Vitaminas','Vitamina D3 2000UI 60 caps da VitaPlus: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para vitaminas e para elevar sua rotina.',39.9,NULL,150,4.8,870,'','[]'::jsonb,NULL,NULL,'{"Marca":"VitaPlus","Categoria":"Vitaminas","Código":"FS-1006","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p008','omega-3-1000mg-120-caps','Ômega 3 1000mg 120 caps','Nutrion','suplementos','Vitaminas','Ômega 3 1000mg 120 caps da Nutrion: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para vitaminas e para elevar sua rotina.',69.9,NULL,0,4.6,302,'','[]'::jsonb,NULL,NULL,'{"Marca":"Nutrion","Categoria":"Vitaminas","Código":"FS-1007","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p009','pre-treino-explosion-300g','Pré-treino Explosion 300g','IronLab','suplementos','Pré-treino','Pré-treino Explosion 300g da IronLab: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para pré-treino e para elevar sua rotina.',149.9,119.9,25,4.4,377,'','[{"label":"Sabor","options":["Chocolate","Baunilha","Morango","Cookies"]}]'::jsonb,NULL,NULL,'{"Marca":"IronLab","Categoria":"Pré-treino","Código":"FS-1008","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p010','termogenico-burn-caps-60','Termogênico Burn Caps 60','MaxForce','suplementos','Termogênicos','Termogênico Burn Caps 60 da MaxForce: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para termogênicos e para elevar sua rotina.',99.9,NULL,60,4.2,210,'','[]'::jsonb,NULL,NULL,'{"Marca":"MaxForce","Categoria":"Termogênicos","Código":"FS-1009","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p011','camiseta-dry-fit-masculina','Camiseta Dry Fit Masculina','Franc Wear','roupas','Masculino','Camiseta Dry Fit Masculina da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para masculino e para elevar sua rotina.',89.9,69.9,90,4.6,450,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Masculino","Código":"FS-1010","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p012','regata-performance-masculina','Regata Performance Masculina','Pulse','roupas','Masculino','Regata Performance Masculina da Pulse: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para masculino e para elevar sua rotina.',69.9,NULL,45,4.4,128,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Pulse","Categoria":"Masculino","Código":"FS-1011","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p013','legging-compressao-feminina','Legging Compressão Feminina','Franc Wear','roupas','Feminino','Legging Compressão Feminina da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para feminino e para elevar sua rotina.',149.9,119.9,70,4.8,812,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Feminino","Código":"FS-1012","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p014','top-fitness-alta-sustentacao','Top Fitness Alta Sustentação','Pulse','roupas','Feminino','Top Fitness Alta Sustentação da Pulse: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para feminino e para elevar sua rotina.',99.9,NULL,38,4.7,333,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Pulse","Categoria":"Feminino","Código":"FS-1013","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p015','conjunto-fitness-seamless','Conjunto Fitness Seamless','Pulse','roupas','Fitness','Conjunto Fitness Seamless da Pulse: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para fitness e para elevar sua rotina.',219.9,179.9,22,4.6,190,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Pulse","Categoria":"Fitness","Código":"FS-1014","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p016','shorts-treino-2-em-1','Shorts Treino 2 em 1','Franc Wear','roupas','Fitness','Shorts Treino 2 em 1 da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para fitness e para elevar sua rotina.',109.9,NULL,55,4.5,221,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Fitness","Código":"FS-1015","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p017','tenis-corrida-velocity','Tênis Corrida Velocity','Stride','calcados','Corrida','Tênis Corrida Velocity da Stride: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para corrida e para elevar sua rotina.',499.9,399.9,30,4.8,640,'','[{"label":"Tamanho","options":["37","38","39","40","41","42","43"]},{"label":"Cor","options":["Preto/Verde","Preto"]}]'::jsonb,'{"Preto"}','{"37","38","39","40","41","42","43"}','{"Marca":"Stride","Categoria":"Corrida","Código":"FS-1016","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p018','tenis-corrida-cloud-run','Tênis Corrida Cloud Run','AeroStep','calcados','Corrida','Tênis Corrida Cloud Run da AeroStep: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para corrida e para elevar sua rotina.',649.9,NULL,12,4.7,288,'','[{"label":"Tamanho","options":["37","38","39","40","41","42","43"]},{"label":"Cor","options":["Preto/Verde","Preto"]}]'::jsonb,'{"Preto"}','{"37","38","39","40","41","42","43"}','{"Marca":"AeroStep","Categoria":"Corrida","Código":"FS-1017","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p019','tenis-treino-cross-grip','Tênis Treino Cross Grip','Stride','calcados','Treino','Tênis Treino Cross Grip da Stride: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para treino e para elevar sua rotina.',389.9,349.9,40,4.6,302,'','[{"label":"Tamanho","options":["37","38","39","40","41","42","43"]},{"label":"Cor","options":["Preto/Verde","Preto"]}]'::jsonb,'{"Preto"}','{"37","38","39","40","41","42","43"}','{"Marca":"Stride","Categoria":"Treino","Código":"FS-1018","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p020','tenis-casual-urban','Tênis Casual Urban','AeroStep','calcados','Casual','Tênis Casual Urban da AeroStep: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para casual e para elevar sua rotina.',299.9,NULL,65,4.4,154,'','[{"label":"Tamanho","options":["37","38","39","40","41","42","43"]},{"label":"Cor","options":["Preto/Verde","Preto"]}]'::jsonb,'{"Preto"}','{"37","38","39","40","41","42","43"}','{"Marca":"AeroStep","Categoria":"Casual","Código":"FS-1019","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p021','chinelo-slide-recovery','Chinelo Slide Recovery','Stride','calcados','Casual','Chinelo Slide Recovery da Stride: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para casual e para elevar sua rotina.',129.9,99.9,100,4.5,410,'','[{"label":"Tamanho","options":["37","38","39","40","41","42","43"]},{"label":"Cor","options":["Preto/Verde","Preto"]}]'::jsonb,'{"Preto"}','{"37","38","39","40","41","42","43"}','{"Marca":"Stride","Categoria":"Casual","Código":"FS-1020","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p022','fone-bluetooth-anc-pro','Fone Bluetooth ANC Pro','Sonix','eletronicos','Fones','Fone Bluetooth ANC Pro da Sonix: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para fones e para elevar sua rotina.',899.9,699.9,18,4.8,940,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Sonix","Categoria":"Fones","Código":"FS-1021","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p023','fone-esportivo-tws-sport','Fone Esportivo TWS Sport','Sonix','eletronicos','Fones','Fone Esportivo TWS Sport da Sonix: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para fones e para elevar sua rotina.',349.9,NULL,60,4.5,612,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Sonix","Categoria":"Fones","Código":"FS-1022","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p024','headphone-studio-wireless','Headphone Studio Wireless','Volta','eletronicos','Fones','Headphone Studio Wireless da Volta: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para fones e para elevar sua rotina.',1199.9,NULL,9,4.7,205,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Volta","Categoria":"Fones","Código":"FS-1023","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p025','smartwatch-fit-gps','Smartwatch Fit GPS','Pulsar','eletronicos','Smartwatches','Smartwatch Fit GPS da Pulsar: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para smartwatches e para elevar sua rotina.',1299.9,1049.9,25,4.6,488,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Pulsar","Categoria":"Smartwatches","Código":"FS-1024","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p026','smartwatch-active-lite','Smartwatch Active Lite','Pulsar','eletronicos','Smartwatches','Smartwatch Active Lite da Pulsar: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para smartwatches e para elevar sua rotina.',499.9,NULL,70,4.3,360,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Pulsar","Categoria":"Smartwatches","Código":"FS-1025","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p027','smartphone-nova-x-256gb','Smartphone Nova X 256GB','Nova','eletronicos','Celulares','Smartphone Nova X 256GB da Nova: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para celulares e para elevar sua rotina.',3499.9,2999.9,14,4.7,721,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Nova","Categoria":"Celulares","Código":"FS-1026","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p028','smartphone-nova-lite-128gb','Smartphone Nova Lite 128GB','Nova','eletronicos','Celulares','Smartphone Nova Lite 128GB da Nova: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para celulares e para elevar sua rotina.',1799.9,NULL,33,4.4,298,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Nova","Categoria":"Celulares","Código":"FS-1027","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p029','carregador-turbo-65w-usb-c','Carregador Turbo 65W USB-C','Volta','eletronicos','Acessórios','Carregador Turbo 65W USB-C da Volta: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para acessórios e para elevar sua rotina.',179.9,139.9,140,4.6,520,'','[{"label":"Cor","options":["Preto","Grafite"]}]'::jsonb,'{"Preto","Grafite"}',NULL,'{"Marca":"Volta","Categoria":"Acessórios","Código":"FS-1028","Garantia":"12 meses","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p030','garrafa-termica-inox-750ml','Garrafa Térmica Inox 750ml','Hōme','casa','Cozinha','Garrafa Térmica Inox 750ml da Hōme: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para cozinha e para elevar sua rotina.',129.9,99.9,85,4.8,670,'','[]'::jsonb,NULL,NULL,'{"Marca":"Hōme","Categoria":"Cozinha","Código":"FS-1029","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p031','caneca-ceramica-artesanal','Caneca Cerâmica Artesanal','Hōme','casa','Cozinha','Caneca Cerâmica Artesanal da Hōme: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para cozinha e para elevar sua rotina.',59.9,NULL,50,4.6,140,'','[]'::jsonb,NULL,NULL,'{"Marca":"Hōme","Categoria":"Cozinha","Código":"FS-1030","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p032','difusor-de-aromas-bambu','Difusor de Aromas Bambu','Hōme','casa','Decoração','Difusor de Aromas Bambu da Hōme: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para decoração e para elevar sua rotina.',89.9,NULL,40,4.5,112,'','[]'::jsonb,NULL,NULL,'{"Marca":"Hōme","Categoria":"Decoração","Código":"FS-1031","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p033','kit-potes-hermeticos-6-pcs','Kit Potes Herméticos 6 pçs','Casa Viva','casa','Organização','Kit Potes Herméticos 6 pçs da Casa Viva: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para organização e para elevar sua rotina.',149.9,119.9,0,4.4,230,'','[]'::jsonb,NULL,NULL,'{"Marca":"Casa Viva","Categoria":"Organização","Código":"FS-1032","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p034','serum-vitamina-c-30ml','Sérum Vitamina C 30ml','Derma Pure','beleza-e-saude','Skincare','Sérum Vitamina C 30ml da Derma Pure: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para skincare e para elevar sua rotina.',119.9,89.9,75,4.7,890,'','[]'::jsonb,NULL,NULL,'{"Marca":"Derma Pure","Categoria":"Skincare","Código":"FS-1033","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p035','hidratante-facial-fps-30','Hidratante Facial FPS 30','Derma Pure','beleza-e-saude','Skincare','Hidratante Facial FPS 30 da Derma Pure: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para skincare e para elevar sua rotina.',79.9,NULL,95,4.6,410,'','[]'::jsonb,NULL,NULL,'{"Marca":"Derma Pure","Categoria":"Skincare","Código":"FS-1034","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p036','shampoo-fortalecedor-300ml','Shampoo Fortalecedor 300ml','Natura Lab','beleza-e-saude','Cabelo','Shampoo Fortalecedor 300ml da Natura Lab: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para cabelo e para elevar sua rotina.',49.9,NULL,110,4.4,198,'','[]'::jsonb,NULL,NULL,'{"Marca":"Natura Lab","Categoria":"Cabelo","Código":"FS-1035","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p037','oleo-de-massagem-relax','Óleo de Massagem Relax','Natura Lab','beleza-e-saude','Bem-estar','Óleo de Massagem Relax da Natura Lab: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para bem-estar e para elevar sua rotina.',69.9,59.9,44,4.5,156,'','[]'::jsonb,NULL,NULL,'{"Marca":"Natura Lab","Categoria":"Bem-estar","Código":"FS-1036","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p038','kit-halteres-emborrachados-2x5kg','Kit Halteres Emborrachados 2x5kg','IronFit','esportes','Musculação','Kit Halteres Emborrachados 2x5kg da IronFit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para musculação e para elevar sua rotina.',219.9,189.9,28,4.7,340,'','[]'::jsonb,NULL,NULL,'{"Marca":"IronFit","Categoria":"Musculação","Código":"FS-1037","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p039','tapete-yoga-antiderrapante','Tapete Yoga Antiderrapante','Zen Move','esportes','Yoga','Tapete Yoga Antiderrapante da Zen Move: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para yoga e para elevar sua rotina.',139.9,NULL,60,4.6,402,'','[]'::jsonb,NULL,NULL,'{"Marca":"Zen Move","Categoria":"Yoga","Código":"FS-1038","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p040','corda-de-pular-rolamento','Corda de Pular Rolamento','IronFit','esportes','Musculação','Corda de Pular Rolamento da IronFit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para musculação e para elevar sua rotina.',49.9,39.9,150,4.5,288,'','[]'::jsonb,NULL,NULL,'{"Marca":"IronFit","Categoria":"Musculação","Código":"FS-1039","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p041','faixas-elasticas-kit-5','Faixas Elásticas Kit 5','Zen Move','esportes','Musculação','Faixas Elásticas Kit 5 da Zen Move: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para musculação e para elevar sua rotina.',79.9,NULL,90,4.6,310,'','[]'::jsonb,NULL,NULL,'{"Marca":"Zen Move","Categoria":"Musculação","Código":"FS-1040","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p042','mochila-trilha-30l','Mochila Trilha 30L','Outpeak','esportes','Outdoor','Mochila Trilha 30L da Outpeak: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para outdoor e para elevar sua rotina.',279.9,229.9,20,4.7,176,'','[]'::jsonb,NULL,NULL,'{"Marca":"Outpeak","Categoria":"Outdoor","Código":"FS-1041","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p043','caderno-universitario-10-materias-200fls','Caderno Universitário 10 Matérias 200fls','Caderno Co.','papelaria','Cadernos','Caderno Universitário 10 Matérias 200fls da Caderno Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para cadernos e para elevar sua rotina.',49.9,39.9,300,4.8,1520,'','[]'::jsonb,NULL,NULL,'{"Marca":"Caderno Co.","Categoria":"Cadernos","Código":"FS-1042","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p044','caderno-inteligente-discos-a5','Caderno Inteligente Discos A5','Smart Note','papelaria','Cadernos','Caderno Inteligente Discos A5 da Smart Note: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para cadernos e para elevar sua rotina.',119.9,NULL,80,4.9,870,'','[]'::jsonb,NULL,NULL,'{"Marca":"Smart Note","Categoria":"Cadernos","Código":"FS-1043","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","new"}'::text[],'own'),
('p045','caderno-pontilhado-capa-dura-a5','Caderno Pontilhado Capa Dura A5','Franc Paper','papelaria','Cadernos','Caderno Pontilhado Capa Dura A5 da Franc Paper: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para cadernos e para elevar sua rotina.',54.9,NULL,120,4.7,312,'','[]'::jsonb,NULL,NULL,'{"Marca":"Franc Paper","Categoria":"Cadernos","Código":"FS-1044","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p046','planner-2027-semanal-capa-dura','Planner 2027 Semanal Capa Dura','Franc Paper','papelaria','Organização','Planner 2027 Semanal Capa Dura da Franc Paper: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para organização e para elevar sua rotina.',79.9,64.9,150,4.8,640,'','[]'::jsonb,NULL,NULL,'{"Marca":"Franc Paper","Categoria":"Organização","Código":"FS-1045","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new","deal"}'::text[],'own'),
('p047','agenda-escolar-2027','Agenda Escolar 2027','Caderno Co.','papelaria','Organização','Agenda Escolar 2027 da Caderno Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para organização e para elevar sua rotina.',39.9,NULL,200,4.6,410,'','[]'::jsonb,NULL,NULL,'{"Marca":"Caderno Co.","Categoria":"Organização","Código":"FS-1046","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p048','kit-canetas-gel-0-7-com-12-cores','Kit Canetas Gel 0.7 com 12 cores','Linea','papelaria','Escrita','Kit Canetas Gel 0.7 com 12 cores da Linea: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para escrita e para elevar sua rotina.',44.9,34.9,250,4.7,980,'','[]'::jsonb,NULL,NULL,'{"Marca":"Linea","Categoria":"Escrita","Código":"FS-1047","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p049','marca-texto-pastel-6-unidades','Marca-texto Pastel 6 unidades','Tinta Viva','papelaria','Escrita','Marca-texto Pastel 6 unidades da Tinta Viva: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para escrita e para elevar sua rotina.',32.9,NULL,180,4.8,760,'','[]'::jsonb,NULL,NULL,'{"Marca":"Tinta Viva","Categoria":"Escrita","Código":"FS-1048","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p050','lapiseira-0-5-grafites-borracha','Lapiseira 0.5 + Grafites + Borracha','Linea','papelaria','Escrita','Lapiseira 0.5 + Grafites + Borracha da Linea: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para escrita e para elevar sua rotina.',29.9,24.9,220,4.6,520,'','[]'::jsonb,NULL,NULL,'{"Marca":"Linea","Categoria":"Escrita","Código":"FS-1049","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p051','estojo-box-3-divisorias','Estojo Box 3 Divisórias','Franc Paper','papelaria','Mochilas e estojos','Estojo Box 3 Divisórias da Franc Paper: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para mochilas e estojos e para elevar sua rotina.',59.9,NULL,90,4.5,280,'','[]'::jsonb,NULL,NULL,'{"Marca":"Franc Paper","Categoria":"Mochilas e estojos","Código":"FS-1050","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p052','mochila-escolar-notebook-15-6','Mochila Escolar Notebook 15,6"','Outpeak','papelaria','Mochilas e estojos','Mochila Escolar Notebook 15,6" da Outpeak: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para mochilas e estojos e para elevar sua rotina.',199.9,169.9,60,4.7,430,'','[]'::jsonb,NULL,NULL,'{"Marca":"Outpeak","Categoria":"Mochilas e estojos","Código":"FS-1051","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p053','fichario-universitario-4-argolas','Fichário Universitário 4 Argolas','Caderno Co.','papelaria','Organização','Fichário Universitário 4 Argolas da Caderno Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para organização e para elevar sua rotina.',89.9,NULL,70,4.6,215,'','[]'::jsonb,NULL,NULL,'{"Marca":"Caderno Co.","Categoria":"Organização","Código":"FS-1052","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p054','kit-volta-as-aulas-2027-fundamental','Kit Volta às Aulas 2027 Fundamental','Franc Paper','papelaria','Kits volta às aulas','Kit Volta às Aulas 2027 Fundamental da Franc Paper: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para kits volta às aulas e para elevar sua rotina.',189.9,149.9,100,4.8,340,'','[]'::jsonb,NULL,NULL,'{"Marca":"Franc Paper","Categoria":"Kits volta às aulas","Código":"FS-1053","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new","deal"}'::text[],'own'),
('p055','kit-volta-as-aulas-2027-universitario','Kit Volta às Aulas 2027 Universitário','Franc Paper','papelaria','Kits volta às aulas','Kit Volta às Aulas 2027 Universitário da Franc Paper: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para kits volta às aulas e para elevar sua rotina.',249.9,199.9,80,4.9,210,'','[]'::jsonb,NULL,NULL,'{"Marca":"Franc Paper","Categoria":"Kits volta às aulas","Código":"FS-1054","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new","bestseller"}'::text[],'own'),
('p056','legging-cintura-alta-basica','Legging Cintura Alta Básica','Franc Wear','roupas','Leggings','Legging Cintura Alta Básica da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',79.9,64.9,150,4.7,1120,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Leggings","Código":"FS-1055","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p057','legging-empina-bumbum-scrunch','Legging Empina Bumbum (Scrunch)','Pulse','roupas','Leggings','Legging Empina Bumbum (Scrunch) da Pulse: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',119.9,99.9,90,4.8,980,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Pulse","Categoria":"Leggings","Código":"FS-1056","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p058','legging-flare-cintura-alta','Legging Flare Cintura Alta','Bella Fit','roupas','Leggings','Legging Flare Cintura Alta da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',129.9,NULL,70,4.6,410,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Leggings","Código":"FS-1057","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p059','legging-estampada-floral','Legging Estampada Floral','Bella Fit','roupas','Leggings','Legging Estampada Floral da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',99.9,NULL,60,4.5,260,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Leggings","Código":"FS-1058","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p060','legging-termica-peluciada','Legging Térmica Peluciada','Franc Wear','roupas','Leggings','Legging Térmica Peluciada da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',139.9,109.9,45,4.7,330,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Leggings","Código":"FS-1059","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p061','legging-com-bolso-lateral','Legging com Bolso Lateral','Pulse','roupas','Leggings','Legging com Bolso Lateral da Pulse: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',109.9,NULL,80,4.8,540,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Pulse","Categoria":"Leggings","Código":"FS-1060","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p062','legging-cirre-efeito-couro','Legging Cirré Efeito Couro','Bella Fit','roupas','Leggings','Legging Cirré Efeito Couro da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para leggings e para elevar sua rotina.',149.9,NULL,35,4.6,190,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde","Nude"]}]'::jsonb,'{"Preto","Grafite","Verde","Nude"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Leggings","Código":"FS-1061","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p063','bermuda-biker-feminina','Bermuda Biker Feminina','Pulse','roupas','Feminino','Bermuda Biker Feminina da Pulse: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para feminino e para elevar sua rotina.',69.9,59.9,100,4.6,380,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Pulse","Categoria":"Feminino","Código":"FS-1062","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p064','macaquinho-fitness-feminino','Macaquinho Fitness Feminino','Bella Fit','roupas','Feminino','Macaquinho Fitness Feminino da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para feminino e para elevar sua rotina.',159.9,NULL,40,4.7,220,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Feminino","Código":"FS-1063","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p065','cropped-canelado-feminino','Cropped Canelado Feminino','Franc Wear','roupas','Feminino','Cropped Canelado Feminino da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para feminino e para elevar sua rotina.',49.9,NULL,120,4.5,310,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Feminino","Código":"FS-1064","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p066','vestido-midi-canelado','Vestido Midi Canelado','Bella Fit','roupas','Feminino','Vestido Midi Canelado da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para feminino e para elevar sua rotina.',139.9,119.9,30,4.6,150,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Grafite","Verde"]}]'::jsonb,'{"Preto","Grafite","Verde"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Feminino","Código":"FS-1065","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"deal"}'::text[],'own'),
('p067','kit-5-calcinhas-algodao','Kit 5 Calcinhas Algodão','Íntima Co.','roupas','Moda íntima','Kit 5 Calcinhas Algodão da Íntima Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',69.9,54.9,200,4.7,1340,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Íntima Co.","Categoria":"Moda íntima","Código":"FS-1066","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p068','kit-3-calcinhas-sem-costura','Kit 3 Calcinhas Sem Costura','Íntima Co.','roupas','Moda íntima','Kit 3 Calcinhas Sem Costura da Íntima Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',59.9,NULL,150,4.8,870,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Íntima Co.","Categoria":"Moda íntima","Código":"FS-1067","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p069','sutia-sem-aro-conforto','Sutiã Sem Aro Conforto','Íntima Co.','roupas','Moda íntima','Sutiã Sem Aro Conforto da Íntima Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',79.9,NULL,90,4.6,520,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Íntima Co.","Categoria":"Moda íntima","Código":"FS-1068","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p070','sutia-com-bojo-liso','Sutiã com Bojo Liso','Bella Fit','roupas','Moda íntima','Sutiã com Bojo Liso da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',89.9,74.9,70,4.5,410,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Moda íntima","Código":"FS-1069","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p071','conjunto-renda-delicada','Conjunto Renda Delicada','Bella Fit','roupas','Moda íntima','Conjunto Renda Delicada da Bella Fit: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',119.9,NULL,40,4.7,260,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Bella Fit","Categoria":"Moda íntima","Código":"FS-1070","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p072','body-modelador-feminino','Body Modelador Feminino','Íntima Co.','roupas','Moda íntima','Body Modelador Feminino da Íntima Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',129.9,109.9,35,4.6,180,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Íntima Co.","Categoria":"Moda íntima","Código":"FS-1071","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{"new"}'::text[],'own'),
('p073','pijama-feminino-algodao','Pijama Feminino Algodão','Íntima Co.','roupas','Moda íntima','Pijama Feminino Algodão da Íntima Co.: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',99.9,NULL,60,4.8,290,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Íntima Co.","Categoria":"Moda íntima","Código":"FS-1072","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p074','kit-3-meias-soquete','Kit 3 Meias Soquete','Franc Wear','roupas','Moda íntima','Kit 3 Meias Soquete da Franc Wear: desenvolvido para quem busca qualidade e desempenho no dia a dia. Materiais selecionados, acabamento premium e garantia de procedência. Ideal para moda íntima e para elevar sua rotina.',29.9,NULL,300,4.5,640,'','[{"label":"Tamanho","options":["P","M","G","GG"]},{"label":"Cor","options":["Preto","Nude","Branco","Mescla"]}]'::jsonb,'{"Preto","Nude","Branco","Mescla"}','{"P","M","G","GG"}','{"Marca":"Franc Wear","Categoria":"Moda íntima","Código":"FS-1073","Garantia":"90 dias","Origem":"Nacional"}'::jsonb,'{}'::text[],'own'),
('p075','topo-de-bolo-personalizado-tema-a-escolha','Topo de Bolo Personalizado (Tema à escolha)','Franc Festas','papelaria','Topos de bolo','Topo de Bolo Personalizado (Tema à escolha). Personalizado com o nome, a idade e o tema que você escolher. Após a compra, envie os dados e fotos pelo WhatsApp; a arte é aprovada por você antes da produção. Prazo de produção: 2 a 4 dias úteis.',34.9,29.9,999,4.9,760,'','[{"label":"Tema","options":["Aniversário","Infantil","Futebol","Princesas","Chá revelação","Casamento"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Festas","Categoria":"Topos de bolo","Código":"FS-1074","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"bestseller","deal"}'::text[],'own'),
('p076','topo-de-bolo-3d-camadas','Topo de Bolo 3D Camadas','Franc Festas','papelaria','Topos de bolo','Topo de Bolo 3D Camadas. Personalizado com o nome, a idade e o tema que você escolher. Após a compra, envie os dados e fotos pelo WhatsApp; a arte é aprovada por você antes da produção. Prazo de produção: 2 a 4 dias úteis.',54.9,NULL,999,4.8,320,'','[{"label":"Tema","options":["Aniversário","Infantil","Futebol","Princesas","Chá revelação","Casamento"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Festas","Categoria":"Topos de bolo","Código":"FS-1075","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"new"}'::text[],'own'),
('p077','topo-de-bolo-acrilico-espelhado-com-nome','Topo de Bolo Acrílico Espelhado com Nome','Franc Festas','papelaria','Topos de bolo','Topo de Bolo Acrílico Espelhado com Nome. Personalizado com o nome, a idade e o tema que você escolher. Após a compra, envie os dados e fotos pelo WhatsApp; a arte é aprovada por você antes da produção. Prazo de produção: 2 a 4 dias úteis.',69.9,NULL,999,4.9,210,'','[{"label":"Tema","options":["Aniversário","Infantil","Futebol","Princesas","Chá revelação","Casamento"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Festas","Categoria":"Topos de bolo","Código":"FS-1076","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"new"}'::text[],'own'),
('p078','kit-festa-personalizado-topo-20-toppers','Kit Festa Personalizado (topo + 20 toppers)','Franc Festas','papelaria','Topos de bolo','Kit Festa Personalizado (topo + 20 toppers). Personalizado com o nome, a idade e o tema que você escolher. Após a compra, envie os dados e fotos pelo WhatsApp; a arte é aprovada por você antes da produção. Prazo de produção: 2 a 4 dias úteis.',89.9,74.9,999,4.8,180,'','[{"label":"Tema","options":["Aniversário","Infantil","Futebol","Princesas","Chá revelação","Casamento"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Festas","Categoria":"Topos de bolo","Código":"FS-1077","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{}'::text[],'own'),
('p079','encadernacao-espiral-ate-100-folhas','Encadernação Espiral até 100 folhas','Franc Print','papelaria','Encadernação','Encadernação Espiral até 100 folhas. Envie seu arquivo em PDF pelo WhatsApp ou e-mail após a compra. Imprimimos (se necessário) e encadernamos com acabamento profissional. Prazo: 1 a 2 dias úteis + frete ou retirada.',9.9,NULL,999,4.8,640,'','[{"label":"Capa","options":["Transparente","Preta","Personalizada"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Encadernação","Código":"FS-1078","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p080','encadernacao-espiral-ate-300-folhas','Encadernação Espiral até 300 folhas','Franc Print','papelaria','Encadernação','Encadernação Espiral até 300 folhas. Envie seu arquivo em PDF pelo WhatsApp ou e-mail após a compra. Imprimimos (se necessário) e encadernamos com acabamento profissional. Prazo: 1 a 2 dias úteis + frete ou retirada.',14.9,NULL,999,4.8,310,'','[{"label":"Capa","options":["Transparente","Preta","Personalizada"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Encadernação","Código":"FS-1079","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{}'::text[],'own'),
('p081','encadernacao-wire-o-premium','Encadernação Wire-o Premium','Franc Print','papelaria','Encadernação','Encadernação Wire-o Premium. Envie seu arquivo em PDF pelo WhatsApp ou e-mail após a compra. Imprimimos (se necessário) e encadernamos com acabamento profissional. Prazo: 1 a 2 dias úteis + frete ou retirada.',19.9,NULL,999,4.9,150,'','[{"label":"Capa","options":["Transparente","Preta","Personalizada"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Encadernação","Código":"FS-1080","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"new"}'::text[],'own'),
('p082','encadernacao-capa-dura-tcc','Encadernação Capa Dura (TCC)','Franc Print','papelaria','Encadernação','Encadernação Capa Dura (TCC). Envie seu arquivo em PDF pelo WhatsApp ou e-mail após a compra. Imprimimos (se necessário) e encadernamos com acabamento profissional. Prazo: 1 a 2 dias úteis + frete ou retirada.',49.9,44.9,999,4.9,220,'','[{"label":"Capa","options":["Transparente","Preta","Personalizada"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Encadernação","Código":"FS-1081","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"deal"}'::text[],'own'),
('p083','impressao-online-p-b-por-pagina','Impressão Online P&B (por página)','Franc Print','papelaria','Impressão online','Impressão Online P&B (por página). Xerox online: compre a quantidade de páginas desejada e envie seu arquivo em PDF pelo WhatsApp ou e-mail. Conferimos o arquivo antes de imprimir. Prazo: 1 dia útil + frete ou retirada.',0.3,NULL,99999,4.7,1980,'','[{"label":"Papel","options":["Sulfite 75g","Sulfite 90g","Couché 150g"]},{"label":"Lados","options":["Frente","Frente e verso"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Impressão online","Código":"FS-1082","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"bestseller"}'::text[],'own'),
('p084','impressao-online-colorida-por-pagina','Impressão Online Colorida (por página)','Franc Print','papelaria','Impressão online','Impressão Online Colorida (por página). Xerox online: compre a quantidade de páginas desejada e envie seu arquivo em PDF pelo WhatsApp ou e-mail. Conferimos o arquivo antes de imprimir. Prazo: 1 dia útil + frete ou retirada.',1.2,NULL,99999,4.7,1240,'','[{"label":"Papel","options":["Sulfite 75g","Sulfite 90g","Couché 150g"]},{"label":"Lados","options":["Frente","Frente e verso"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Impressão online","Código":"FS-1083","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{}'::text[],'own'),
('p085','impressao-de-apostila-completa-ate-100-pags','Impressão de Apostila Completa (até 100 págs)','Franc Print','papelaria','Impressão online','Impressão de Apostila Completa (até 100 págs). Xerox online: compre a quantidade de páginas desejada e envie seu arquivo em PDF pelo WhatsApp ou e-mail. Conferimos o arquivo antes de imprimir. Prazo: 1 dia útil + frete ou retirada.',29.9,24.9,999,4.8,410,'','[{"label":"Papel","options":["Sulfite 75g","Sulfite 90g","Couché 150g"]},{"label":"Lados","options":["Frente","Frente e verso"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Impressão online","Código":"FS-1084","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{"new","deal"}'::text[],'own'),
('p086','plastificacao-a4','Plastificação A4','Franc Print','papelaria','Impressão online','Plastificação A4. Xerox online: compre a quantidade de páginas desejada e envie seu arquivo em PDF pelo WhatsApp ou e-mail. Conferimos o arquivo antes de imprimir. Prazo: 1 dia útil + frete ou retirada.',4.9,NULL,999,4.6,190,'','[{"label":"Papel","options":["Sulfite 75g","Sulfite 90g","Couché 150g"]},{"label":"Lados","options":["Frente","Frente e verso"]}]'::jsonb,NULL,NULL,'{"Marca":"Franc Print","Categoria":"Impressão online","Código":"FS-1085","Garantia":"90 dias","Origem":"Serviço sob encomenda"}'::jsonb,'{}'::text[],'own')
ON CONFLICT (id) DO NOTHING;
