/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PaginaSlugRouteImport } from './routes/pagina.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaSlugRoute = PaginaSlugRouteImport.update({
  id: '/pagina/$slug',
  path: '/pagina/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/favoritos': typeof FavoritosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pagina/$slug': typeof PaginaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/favoritos': typeof FavoritosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pagina/$slug': typeof PaginaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/favoritos': typeof FavoritosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/pagina/$slug': typeof PaginaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/busca' | '/favoritos' | '/categoria/$slug' | '/pagina/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/busca' | '/favoritos' | '/categoria/$slug' | '/pagina/$slug'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/favoritos'
    | '/categoria/$slug'
    | '/pagina/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  FavoritosRoute: typeof FavoritosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PaginaSlugRoute: typeof PaginaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagina/$slug': {
      id: '/pagina/$slug'
      path: '/pagina/$slug'
      fullPath: '/pagina/$slug'
      preLoaderRoute: typeof PaginaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  FavoritosRoute: FavoritosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PaginaSlugRoute: PaginaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
